@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.simpleabsorption;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
