# Mod
mod_id=simple_absorption
mod_version=1.3.0

# Dependencies
minecraft_version=1.20.1
minecraft_range=[1.20.1]

loader_range=[33,)
forge_version=47.4.9
forge_range=[47.4.9,)
parchment_version=2022.09.04

# Optional Dependencies
jei_version=15.20.0.116
mantle_version=1.11.94
tinkers_version=3.11.0.148
# we depend on tinkers removing its use for golden apples and having steel shards, both part of 3.11.0
tinkers_range=[3.11.0.148,4)
