modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/KnightMiner/SimpleAbsorption/issues/"
[[mods]]
modId="simple_absorption"
version="${version}"
displayName="Simple Absorption"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-absorption"
logoFile="logo.png"
credits="Inspired by Natural Absorption by Father Toast and Super Hostile by Vechs"
authors="KnightMiner"
description='''
Mod adding a simple absorption shield for the player, restored when the hunger bar is full.
'''
[[dependencies.simple_absorption]] 
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)" #mandatory
    ordering="AFTER"
    side="BOTH"
[[dependencies.simple_absorption]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},]"
    ordering="NONE"
    side="BOTH"
