modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/KnightMiner/SimpleAbsorption/issues/"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Simple Absorption"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-absorption"
logoFile="logo.png"
credits="Inspired by Natural Absorption by Father Toast and Super Hostile by Vechs"
authors="KnightMiner"
description='''
Mod adding a simple absorption shield for the player, restored when the hunger bar is full.
'''
[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}" #mandatory
    ordering="AFTER"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="tconstruct"
    mandatory=false
    versionRange="${tinkers_range}"
    ordering="AFTER"
    side="BOTH"